import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@vagasaservice/ui/src/app/globals.css'

import { Header } from '@vagasaservice/ui/src/components/organisms/Header'
import { MenuItem } from '@vagasaservice/utils/types'
import { Container } from '@vagasaservice/ui/src/components/atoms/Container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VagasAService',
  description: 'Generated by create next app',
}

const MENUITEMS = [
  { label: 'Buscar', href: '/search' },
  { label: 'Reservas', href: '/bookings' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-gray-25`}>
        <Header menuItems={MENUITEMS} />
        <Container>{children}</Container>
      </body>
    </html>
  )
}
