export const frustratedComments = [
    "Preciso de espaço para estacionar ou vou começar uma carona solidária no telhado.",
    "Por que todos os caminhos levam a 'proibido estacionar'?",
    'Em busca do meu lugar feliz... \nAKA uma vaga de estacionamento.',
    "Deveria ter comprado um helicóptero em vez disso.",
    "Se eu tivesse um centavo para cada vaga ocupada, eu seria o dono do estacionamento.",
    'Brb, dando a volta no estacionamento pela centésima vez.',
    "Encontrar uma alma gêmea parece mais fácil do que encontrar uma vaga no estacionamento.",
    'Eu vim, eu vi... Dei a volta no estacionamento',
    "Em um relacionamento com o sinal 'P'.",
    'Envelhecendo à espera de uma vaga de estacionamento',
    'A busca pelo Santo Graal provavelmente foi mais fácil.',
    "Se estacionar fosse um esporte olímpico, eu ainda estaria em último lugar.",
    'Procurando uma vaga para estacionar, envie ajuda.',
    'Começando a sentir falta do meu velho triciclo.',
    "Da próxima vez, comprarei um carro que venha com sua própria vaga de estacionamento.",
    'Quer jogar caça à vaga de estacionamento?',
    'Carro à venda: passa mais tempo procurando estacionamento do que dirigindo',
    'Existe um código de trapaça para estacionamento instantâneo?',
    'Reunião? Haha. Eu nem sequer encontrei um estacionamento',
    "Eu não me inscrevi para esse episódio de 'Guerra de vagas de estacionamento'.",
    "Querida, vou me atrasar. \Estou preso em uma saga de estacionamento.",
    "Tenho certeza de que meu carro está gostando desse \ntour pelo estacionamento.",
    "Não se estaciona simplesmente em uma cidade \nbustacular.",
    "Quem precisa de uma academia quando se tem um treino no estacionamento?",
    "Isso não é um estacionamento, é um esconde-esconde de carros!",
    "Eu não escolhi a vida no estacionamento. \nA vida no estacionamento me escolheu.",
    "Com licença, vou estacionar meu carro em outro fuso horário",
    'Estacionamento: O teste definitivo de paciência.',
    'Um pequeno passo para o homem, \num salto gigante para encontrar uma vaga de estacionamento.',
    'Hora do meu jogo diário de \nSpot the Parking Spot.',
    "Aceito apostas sobre se vou encontrar uma vaga primeiro ou se vou me aposentar.",
    "Se eu tivesse um centavo para cada minuto que passei procurando estacionamento, seria um milionário.",
    "Meu GPS diz 'você chegou ao seu destino', mas onde está o estacionamento?",
    "Já dei tantos círculos que estou ficando tonto. \nOnde está a vaga de estacionamento?",
    "Será que meu carro se cansa tanto quanto eu ao procurar uma vaga?",
    "Procurar estacionamento é o exercício cardiovascular preferido do meu carro.",
    "Um dia, contarei aos meus netos sobre \na grande odisseia do estacionamento.",
    'Acho que acabei de ver uma erva daninha passar...',
    "Siri, encontre a vaga de estacionamento mais próxima, por favor!",
    'Hora de jogar meu jogo menos favorito: \nroleta do estacionamento',
    "Tenho 99 problemas, e estacionamento é um deles.",
    "Juro que as vagas de estacionamento estão tocando cadeiras musicais sem mim.",
    "Se eu passar mais tempo procurando, vou precisar reabastecer.",
    "Estou pensando em adotar um pombo-correio para encontrar vagas de estacionamento para mim.",
    "Não há 'I' em 'park', mas há um 'I' em 'circle \nthe parking lot for the fifth time'.",
    'Aposto que até Colombo encontrou a América mais rápido do que eu consigo encontrar uma vaga no estacionamento',
    "Se eu estacionar mais longe, estarei na cidade vizinha.",
    "Acho que está na hora do meu jogo diário de bingo de vagas de estacionamento.",
    "Procura-se: um tapete mágico, porque Aladdin nunca teve problemas de estacionamento.",
    "Adivinhe quem vai fazer um \nunesperado safári de estacionamento!",
    'Estacionamentos são apenas versões adultas de cadeiras musicais',
    "Será que todas as vagas de estacionamento saíram de férias ou algo assim?",
    "Há dois tipos de pessoas: \nAquelas que encontram estacionamento e aquelas que não encontram. \nAdivinhe qual deles eu sou.",
    "Estacione em qualquer lugar, eles disseram. \Será fácil, eles disseram.",
    "Eu já vi unicórnios, o monstro do Lago Ness, mas uma vaga de estacionamento grátis? Nunca.",
    "Siri, encontre-me a vaga de estacionamento mais próxima, por favor!",
    `\nSiri: "Hmm, há uma vaga a 200 milhas de distância. Pronto para uma viagem de carro?"`,
  ]
  
  export const getRamdomComment = () =>
    frustratedComments[Math.floor(Math.random() * frustratedComments.length)]